---
- name: "5.3.16 | L1 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
    - name: "5.3.16 | L1 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^#ClientAliveInterval|^ClientAliveInterval"
        line: "ClientAliveInterval {{ rhel7cis_sshd['clientaliveinterval'] }}"
        validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
      notify:
          - restart sshd

    - name: "5.3.16 | L1 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^#ClientAliveCountMax|^ClientAliveCountMax"
        line: "ClientAliveCountMax {{ rhel7cis_sshd['clientalivecountmax'] }}"
        validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
      notify:
        - restart sshd

- name: "5.3.18 | L1 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^Banner ((?!/etc/issue.net$)).*$'
      line: "{{ item.line|default(omit) }}"
      insertafter: "{{ item.after|default(omit)}}"
      state: "{{ item.state }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  with_items:
      - { state: absent }
      - { state: present, line: 'Banner /etc/issue.net', after: '#Banner none' }
  notify:
      - restart sshd