---
- name: "AUTOMATED | 5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
      - { regexp: '^ClientAliveInterval|^#ClientAliveInterval', line: 'ClientAliveInterval {{ ubtu20cis_sshd.client_alive_interval }}' }
      - { regexp: '^ClientAliveCountMax|^#ClientAliveCountMax', line: 'ClientAliveCountMax {{ ubtu20cis_sshd.client_alive_count_max }}' }
  notify: restart sshd

- name: "AUTOMATED | 5.3.18 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Banner|^#Banner'
    line: Banner /etc/issue.net
    insertafter: '^# no default banner path'
  notify: restart sshd