---
- name: "AUTOMATED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "AUTOMATED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/cramfs.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: install cramfs /bin/true
            create: yes

      - name: "AUTOMATED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Disable cramfs"
        modprobe:
            name: cramfs
            state: absent

- name: "AUTOMATED | 1.7.1 | PATCH | Ensure message of the day is configured properly"
  template:
      src: motd.j2
      dest: /etc/motd

- name: "AUTOMATED | 1.7.2 | PATCH | Ensure local login warning banner is configured properly"
  template:
      src: issue.j2
      dest: /etc/issue

- name: "AUTOMATED | 1.7.3 | PATCH | Ensure remote login warning banner is configured properly"
  template:
      src: issue.net.j2
      dest: /etc/issue.net

- name: "AUTOMATED | 1.7.4 | PATCH | Ensure permissions on /etc/motd are configured"
  file:
      path: /etc/motd
      owner: root
      group: root
      mode: 0644

- name: "AUTOMATED | 1.7.5 | PATCH | Ensure permissions on /etc/issue are configured"
  file:
      path: /etc/issue
      owner: root
      group: root
      mode: 0644

- name: "AUTOMATED | 1.7.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  file:
      path: /etc/issue.net
      owner: root
      group: root
      mode: 0644